apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gl 
  janus-idp.io/tekton: gl
  backstage.io/kubernetes-id: gl
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gl
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  