apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: gl-gitops
  description: This is GitOps manifest for gl   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: gl
    backstage.io/kubernetes-id: gl 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: gl-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:gl
