apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gl 
  name: gl
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gl 
